# Generated by Django 4.2.4 on 2023-08-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_info_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='email',
        ),
    ]
