# Generated by Django 4.2.4 on 2023-08-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile/'),
        ),
    ]
