# Generated by Django 4.2.4 on 2023-08-16 11:27

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=job.models.image_save),
            preserve_default=False,
        ),
    ]
