# Generated by Django 4.2.4 on 2023-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Full_Time', 'Full_Time'), ('Part_Time', 'Part_Time')], max_length=100),
        ),
    ]
