# Generated by Django 4.2.4 on 2023-08-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
