# Generated by Django 4.2.4 on 2023-09-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.category'),
        ),
    ]
