# Generated by Django 4.2.4 on 2024-02-01 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image'),
        ('job', '0011_alter_job_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
