# Generated by Django 4.2.4 on 2024-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_rename_website_apply_portfolio_alter_apply_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category_name',
            field=models.CharField(blank=True, choices=[('programming', 'Programming'), ('agriculture', 'Agreculture'), ('science', 'Science')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
